### ISSUE TITLE
[BUG] The SQlite auto install fails because there's no release in your repository

### ISSUE THREAD

**Issue by krillin666** [aidenlx/obsidian-zotero#111]
Hi !

Firstly, thank you for this amazing plugin, being able to have automatic updates from Zotero is what I've always wanted. I hope someone uses your API to make a Zotero plugin for Logseq !

I'm trying to install the plugin, through BRAT, but encountered an error when setting up the database. With auto install it tries to download from https://github.com/aidenlx/better-sqlite3/releases/download/8.0.1-mod.1/linux-x64-109.node.gz , but as you can see there's no release in that repo of that version. Thus, the installation fails.
The only release available is the `7.6.2-mod.2`which is older, is it ok to manually install this one ?

**Comment by aidenlx** [comment]
Yeah, I’m updating the release for new platform, now it should work properly
