### ISSUE TITLE
shift+enter in suggester don't insert the secondary markdown citation

### ISSUE THREAD

**Issue by aidenlx** [aidenlx/obsidian-zotero#117]
from #114 

shift+enter just goes to the next line

**Comment by MSBack** [comment]
Hey @aidenlx, is there any news on a fix for this?

**Comment by aidenlx** [comment]
Well it seems like in editor, the editor shortcut with modifier will have highest priority, preventing suggester from working properly. In latest patch, ending slash is used to indicate secondary markdown citation. 

For example, you can enter `[@whatever_query/` and Enter to insert secondary markdown citation.

**Comment by MSBack** [comment]
> Well it seems like in editor, the editor shortcut with modifier will have highest priority, preventing suggester from working properly. In latest patch, ending slash is used to indicate secondary markdown citation. 
> 
> 
> 
> For example, you can enter `[@whatever_query/` and Enter to insert secondary markdown citation. 

That's strange. In Zotero Integration, holding ctrl while pressing enter in the autocompletion suggester inserts the secondary markdown citation format without issues.
