### ISSUE TITLE
Tags in annot template 

### ISSUE THREAD

**Issue by luravoid** [aidenlx/obsidian-zotero#118]
Is there a way to add note tags to annot template?

**Comment by luravoid** [comment]
I tried to add <%= it.tags %> in my template but the result only shows "[object Object]" instead of the tags that I added 

![image](https://user-images.githubusercontent.com/103893901/228960854-d5838e5e-6541-4ce6-b5ed-1f431c88184b.png)
![image](https://user-images.githubusercontent.com/103893901/228960924-09887d8d-cf8d-4abe-9dcd-d97b1be8fe35.png)

**Comment by MSBack** [comment]
Yeah, it works for me.

This is how I add tags to annotations:

First the full `zt-annot.eta` template, so you see the code in context:

```
---
callout: false
---

<% if (it.imgEmbed) { %>
- <%= it.imgEmbed %> ^<%= it.blockID %>\n
<% } %>
<% if (it.comment) { %>
- <% if (it.comment.startsWith('todo ')) { %>[ ] **<%= it.comment.substring(5) %>:**<% } else { %>**<%= it.comment %>:**<% } %> ^<%= it.blockID %>\n
	- ==<%= it.text %>== [p. <%= it.pageLabel %>](zotero://open-pdf/library/items/<%= it.parentItem %>?page=<%= it.pageLabel %>&annotation=<%= it.key %>)<% if (it.tags && it.tags.length > 0) { %> <% = it.tags.map(tag => '#' + tag.name).join(", ") %><% } %> ^<%= it.blockID %>\n
<% } else if (it.text) { %>
- ==<%= it.text %>== [p. <%= it.pageLabel %>](zotero://open-pdf/library/items/<%= it.parentItem %>?page=<%= it.pageLabel %>&annotation=<%= it.key %>)<% if (it.tags && it.tags.length > 0) { %> <% = it.tags.map(tag => '#' + tag.name).join(", ") %><% } %> ^<%= it.blockID %>\n
<% } %>
```

And here's the line just for the tags:

```
<% if (it.tags && it.tags.length > 0) { %> <% = it.tags.map(tag => '#' + tag.name).join(", ") %><% } %>
```
This ensure that tags are start with a `#` and also that they are listed with a comma between them.

If you put the same code into the `zt-note.eta` template, for example in a metadata callout, it will give you the tags associated with the article.

You can see screenshots of how this all looks here: https://forum.obsidian.md/t/obsidian-zotero-import-templates/56901/3?u=feralflora

**Comment by MSBack** [comment]
You can put this after the annotation `<%= it.text %>`:
```
[p. <%= it.pageLabel %>](zotero://open-pdf/library/items/<%= it.parentItem %>?page=<%= it.pageLabel %>&annotation=<%= it.key %>)
```
