### ISSUE TITLE
[Bug] Electron in current version of obsidian is newer than one supported by installed obsidian-zotero plugin

### ISSUE THREAD

**Issue by cs-mshah** [aidenlx/obsidian-zotero#129]
I updated to the new obsidian installer and it broke the obsidian-zotero plugin again:
![Screenshot from 2023-05-03 12-02-29](https://user-images.githubusercontent.com/56499208/235847530-aef31fb4-53e8-4113-a683-3dc18802f3fd.png)
![image](https://user-images.githubusercontent.com/56499208/235847766-22b65a22-81a5-4103-850c-80d871a25f66.png)

Is there a fix for this or this plugin will break everytime the electron version upgrades?

**Comment by aidenlx** [comment]
> Is there a fix for this or this plugin will break everytime the electron version upgrades?

Whenever an new electron release, I have to add it to support list and build a `better-sqlite3` binary for it. So yes, this plugin will break on electron upgrades and require an plugin update to work with latest version.
