### ISSUE TITLE
losing templates when restarting Obsidian

### ISSUE THREAD

**Issue by chickymonkeys** [aidenlx/obsidian-zotero#136]
Hi, I am having the following issue using the plugin on Obsidian installed on MacOS Ventura. It is actually pretty simple to explain. Every time I re-open Obsidian, the literature note template vanishes and goes back to the default templating, not the one I have configured.

Could it be related to the fact that my Vault is in Google Drive for syncing?

**Comment by chickymonkeys** [comment]
My bad, I found the issue.

**Comment by MSBack** [comment]
> My bad, I found the issue.

Well, what was the issue? Was it that you hadn't exported the templates to files from the settings? It might be useful for others to know.
