### ISSUE TITLE
Stuck trying to install zotero-obsidian-note-*.xpi

### ISSUE THREAD

**Issue by ge** [aidenlx/obsidian-zotero#137]
Confused yet hopeful user here.  Problem is that the instructions [here](https://obzt.aidenlx.top/getting-started/install/zotero) saying to install a Zotero plugin(s) (_zotero-obsidian-note-*.xpi_) doesn't work.  The [link](https://github.com/aidenlx/obsidian-zotero/releases/download/zt1.0.1/zotero-obsidian-note-1.0.1.xpi) says that the repository is corrupted and, search as I might in your repositories, I can find only _zotero-obsidian-note-master_, which has no _.xpi_ file in it.

I'm stuck.  How do I continue installing _obsidian-zotero_, which sounds amazing?

**Comment by aidenlx** [comment]
weird, the link you posted jump to download correctly, what error did you seen when open <https://github.com/aidenlx/obsidian-zotero/releases/download/zt1.0.1/zotero-obsidian-note-1.0.1.xpi> on browser?

**Comment by ge** [comment]
> weird, the link you posted jump to download correctly, what error did you seen when open https://github.com/aidenlx/obsidian-zotero/releases/download/zt1.0.1/zotero-obsidian-note-1.0.1.xpi on browser?

[what I see](https://zabouti-east-000.s3.amazonaws.com/photos_for_misc/Screenshot+2023-05-14+at+17.45.34.png)

OTOH, when I pasted the URL into Vivaldi, it downloaded just fine.  I must have too much protection turned on in my Firefox.  

Thanks for your help!  Now onward to trying to get your plugin going.

**Comment by aidenlx** [comment]
lol seems like it treat the xpi as a legacy FireFox extension. Closing this issue now.
