### ISSUE TITLE
[bug]: 在使用过程中报错

### ISSUE THREAD

**Issue by YIRU69** [aidenlx/obsidian-zotero#70]
感谢作者制作这么好用的插件，在使用过程中出现的一些问题，希望能帮忙看看

```
app.js:1 TypeError: Cannot read properties of undefined (reading 'name')
    at yo (plugin:obsidian-zotero-plugin:129:2159)
    at eval (plugin:obsidian-zotero-plugin:193:22143)
    at e.languageDataAt (app.js:1:297298)
    at e.charCategorizer (app.js:1:297457)
    at e.wordAt (app.js:1:297594)
    at ur.ViewPlugin.fromClass.decorations.getDeco (plugin:obsidian-dynamic-highlights:86:20567)
    at new ur.ViewPlugin.fromClass.decorations (plugin:obsidian-dynamic-highlights:86:19921)
    at e.create (app.js:1:348474)
    at e.update (app.js:1:348904)
    at e.setState (app.js:1:436337)
 ```

- 使用过程说明
  1. 下载两个软件的插件，安装使用配置
  2. 开始使用比较完美出现侧边栏的注释，可以拖动，功能都正常
  3. 后面我尝试改动格式，然后侧边栏就不能正常使用了
  4. 我尝试卸载ob的插件，重新安装，还是不能使用侧边栏的拖动功能，侧边栏不显示注释
  5. 以上是代码的报错
  
 - 功能建议
 
1. 是否可以增加对yaml区的定义
2. 是否可以在侧边栏增加搜索功能

**Comment by YIRU69** [comment]
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="plugin:obsidian-zotero-plugin:193" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">plugin:obsidian-zotero-plugin:193</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <div class="console-view-object-properties-section object-value-promise source-code" style="flex: 1 1 auto; padding: 0px; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; position: relative; vertical-align: baseline; color: var(--override-error-text-color) !important; display: inline-block; overflow-wrap: break-word; max-width: 100%; line-height: 1.2;"><div class="tree-outline-disclosure tree-outline-disclosure-hide-overflow" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><ol class="tree-outline hide-selection-when-blurred source-code object-properties-section" role="tree" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; padding: 0px; margin: 0px; z-index: 0; position: relative; color: var(--color-text-primary); display: flex; flex-direction: column; list-style-type: none;"><li title="" role="treeitem" class="parent object-properties-section-root-element" aria-expanded="false" style="box-sizing: border-box; min-width: 0px; min-height: 16px; display: flex; flex-direction: row; text-overflow: ellipsis; white-space: nowrap; position: relative; align-items: center; user-select: text;"><slot style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><span class="console-object console-object-preview" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: pre-wrap; overflow-wrap: break-word; font-style: italic; word-break: break-all;"><span class="object-description" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Promise </span><span class="object-properties-preview" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">{<span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">&lt;fulfilled&gt;</span>: <span class="object-value-undefined" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-disabled);">undefined</span>, <span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">Symbol()</span>: <span class="object-value-object" title="Object" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">{…}</span>}</span></span></slot></li></ol></div></div></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | SD | @ | plugin:obsidian-zotero-plugin:193
-- | -- | -- | --
  | await in SD（异步） |   |  
  | w | @ | plugin:obsidian-zotero-plugin:90
  | C | @ | plugin:obsidian-zotero-plugin:90
  | a | @ | plugin:obsidian-zotero-plugin:90
  | eval | @ | plugin:obsidian-zotero-plugin:90
  | e.tryTrigger | @ | app.js:1
  | e.trigger | @ | app.js:1
  | ll | @ | plugin:obsidian-zotero-plugin:193
  | await in ll（异步） |   |  
  | s | @ | app.js:1
  | l | @ | app.js:1
  | setTimeout（异步） |   |  
  | l | @ | app.js:1
  | setTimeout（异步） |   |  
  | c | @ | app.js:1
  | emit | @ | node:events:390
  | FSWatcher._handle.onchange | @ | node:internal/fs/watchers:212

</span></div>
</body>
</html>

**Comment by aidenlx** [comment]
你更新到1.0.0看下，有问题的话把issue重开吧

**Comment by YIRU69** [comment]
@aidenlx 非常感谢，我大概测试了一下，目前功能看起来都还正常，而且添加了很多功能，正常使用中，再次感谢
