### ISSUE TITLE
[Bug] Error in templater while importing to obsidian

### ISSUE THREAD

**Issue by cs-mshah** [aidenlx/obsidian-zotero#71]
This is what I got when I tried to import to obsidian. I have the notes folder set to `PaperNotes` and templates to `notes/templates/ZtTemplates`
```
plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token '=
```  

```
Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token 'for'
```

"templates/ZtTemplates" is not an indexable file

"templates" is not an indexable file

**Comment by aidenlx** [comment]
can you try latest 1.0.0 and see if the issue persists? Feel free to re-open this issue if you still have similar issue.
