### ISSUE TITLE
Obsidian crash on enabling plugin

### ISSUE THREAD

**Issue by HEmile** [aidenlx/obsidian-zotero#73]
Obsidian crashes whenever I enable the plugin. I couldn't automatically install better-sqlite3 (404 error), and installed https://github.com/aidenlx/better-sqlite3/releases/download/7.6.2-mod.2/darwin-amd64-103.node.gz for my Macbook Pro 2019 (with an intel chip). Probably has something to do with that. 

```[2022-10-26T10:51:47.940] [INFO] obsidian-zotero:main - loading Obsidian Zotero Plugin
plugin:obsidian-zotero-plugin:6 [2022-10-26T10:51:47.950] [INFO] obsidian-zotero:main - Auto refresh set to true
blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58 Error: failed to get libs: no main database opened
    at EX (blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58:13594)
    at Function.<anonymous> (blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58:8438)
    at Function.o (blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58:8276)
    at blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:14:8229
    at blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:14:6948
(anonymous) @ VM114 2aa030d7-41ad-4607-bd11-2c928a499dec:58
await in (anonymous) (async)
o @ VM114 2aa030d7-41ad-4607-bd11-2c928a499dec:58
(anonymous) @ VM114 2aa030d7-41ad-4607-bd11-2c928a499dec:14
(anonymous) @ VM114 2aa030d7-41ad-4607-bd11-2c928a499dec:14
plugin:obsidian-zotero-plugin:6 [2022-10-26T10:51:48.188] [ERROR] obsidian-zotero:main - Error: failed to get libs: no main database opened
    at EX (blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58:13594)
    at Function.<anonymous> (blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58:8438)
    at Function.o (blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:58:8276)
    at blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:14:8229
    at blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:14:6948
blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:48 [2022-10-26T10:51:48.200] [INFO] obsidian-zotero:db-worker - Database opened:  /Users/emile/Zotero/zotero.sqlite
blob:app://obsidian.md/2aa030d7-41ad-4607-bd11-2c928a499dec:48 [2022-10-26T10:51:48.201] [INFO] obsidian-zotero:db-worker - Database opened:  /Users/emile/Zotero/better-bibtex-search.sqlite```

**Comment by Tombychan** [comment]
Same thing happened to me. :/

**Comment by promethean** [comment]
I can't install better-sqlite3 via auto install.  It generates a "request failed 404" response

**Comment by Kullenej** [comment]
I can't install better-sqlite3 via auto install as well. And the link for the manual way leads to a non-working webpage.

**Comment by aidenlx** [comment]
Can you post the link from manual install and attach debug info from obsidian (you can find the command to do so using keyword debug)

**Comment by Kullenej** [comment]
Here is the link from the manual install and a screenshot of what I see when I click it.
https://github.com/aidenlx/better-sqlite3/releases/download/7.6.2-mod.2/darwin-x64-103.node.gz
![Skærmbillede 2022-10-31 kl  08 34 22](https://user-images.githubusercontent.com/86346980/198955752-a9b09782-4077-4e42-b2c7-b7ea9a1e0e72.jpg)

**Comment by Kullenej** [comment]
And here is two log-files from the console log.
[obsidian.md-1667201854803.log](https://github.com/aidenlx/obsidian-zotero/files/9898986/obsidian.md-1667201854803.log)
[obsidian.md-1667201844561.log](https://github.com/aidenlx/obsidian-zotero/files/9898987/obsidian.md-1667201844561.log)

**Comment by aidenlx** [comment]
Could you test if auto-install works properly now?

**Comment by phlind** [comment]
I also manually downloaded better-sqlite3 (same link as in @HEmile's post), after the manual install button did not work. Trying to enable the plugin does turn my Obsidian totally white. I can't even open the developer tools. When I restart Obsidian, the plugin is still deactivated. 

I removed the plugin and tried to install it again now, but better-sqlite3 still seems to be installed, so the same error comes. Can you tell me how to remove it on macOS @aidenlx? Thanks

**Comment by Kullenej** [comment]
It worked with auto-install now! Thanx!!

**Comment by aidenlx** [comment]
@phlind you can go to .obsidian file and delete better-sqlite3-*.node manually. Afterwards you should be able to do auto install

**Comment by HEmile** [comment]
That worked for me :)

**Comment by phlind** [comment]
Yes, It's working now, thanks!
