### ISSUE TITLE
Quick switcher not showing all Zotero database items

### ISSUE THREAD

**Issue by schnps** [aidenlx/obsidian-zotero#76]
There seems to be some wonkiness with the lit note switcher.

1. It seems to only switch by note title, not author (see attach 1 & 2). Is that intentional? If so, can it be modified to search Authors too.
2. I also have a number of items that are in Zotero but are not coming up either by title or author in the Quick Switcher for Lit Notes. (See attach 3&4)

Attempts to diagnose:
- Obviously ran "Refresh Zotero Data" and "Refresh Lit Note Index" in Obsidian
- At first I thought it had to do with ZotFile moving attachments but it happens regardless of if I've run ZotFile on a new entry or not.
- Then I wondered if it was because I have Zotero on two computers and use Zotero's built-in sync, but this happens for files added on either PC.
- Then I ran out of ideas

Any idea what’s going on?

Attachments:
1. ![ztob 1](https://user-images.githubusercontent.com/10359265/198893911-d832cd73-76f4-4ccc-a662-d5e01e3d9d7a.PNG) - Switcher shows Slaughter as author, without searching, so we know the plugin "sees" it.
2. ![ztob 2](https://user-images.githubusercontent.com/10359265/198893917-edfb63ae-9972-4057-973b-44a7191b1fd8.PNG) - Searching Slaughter reveals nothing
3. ![ztob5Capture](https://user-images.githubusercontent.com/10359265/198894509-2f18d86a-bc25-4a74-9f3d-c4101e322e9f.PNG) - But searching by title pulls the article

4. 
![ztob 3](https://user-images.githubusercontent.com/10359265/198894123-90a74150-1ed1-4fe5-a424-d23905bbb5ff.PNG) - Record is in the Zotero database
5. 
![ztob 4](https://user-images.githubusercontent.com/10359265/198894127-63c5edbf-620e-44d1-9c9b-b4f8fdcf7a0d.PNG) - But doesn't show up when searching by "Deep Oper"

**Comment by aidenlx** [comment]
The plugin doesn’t support query by author yet, I’ll mark this a feature request

**Comment by schnps** [comment]
Thanks! However, even searching by title, many of my database items don't show up in the switcher. Happy to split that out into a second issue though.

-------- Original Message --------

**Comment by aidenlx** [comment]
can you try latest 1.0.0 and see if the issue persists? Feel free to re-open this issue if you still have similar issue.
