### ISSUE TITLE
Open existing literature note if present

### ISSUE THREAD

**Issue by HEmile** [aidenlx/obsidian-zotero#78]
When I use the quick switcher and open an entry for which I already have a note in my vault, it creates a new note (eg, 'Note Title 1') instead of opening the existing entry. This used to be the behavior in the citations plugin and was very useful to me.

**Comment by phlind** [comment]
For me it opens the note, when it already exists.

**Comment by aidenlx** [comment]
can you try latest 1.0.0 and see if the issue persists? Feel free to re-open this issue if you still have similar issue.
