### ISSUE TITLE
Is there a way to automatically generate literature notes for all, or a selection of, references in the Zotero database?

### ISSUE THREAD

**Issue by BorgeJorge** [aidenlx/obsidian-zotero#80]
This is a fantastic plugin, thank you! I'm wondering if the following is possible.

I've been highlighting and/or annotating PDF articles for years using Adobe and more recently Okular. Is there a way to automatically sweep through my Zotero library and create Obsidian literature notes for all of my articles at once? (Or is there a way to create literature notes other than one at a time through Quick Switcher that I haven't discovered?) Ideally, it would also be great to have the option to automatically create notes just for all the articles that had highlights/annotations.

Thank you so much for your work on this!

**Comment by mo-seph** [comment]
If I understand right, the Zotero plugin does this - it gives me a command in Zotero, for `Export selected to Obsidian`. It doesn't seem to work for me - perhaps it does for you? (Issue #99 )

**Comment by aidenlx** [comment]
You can try it in latest 1.0.0 plugins, the function is implemented properly (make sure to update both zotero and obsidian plugin!)
