### ISSUE TITLE
Need Help: Citekey No item found for itemID XXXX

### ISSUE THREAD

**Issue by Nat-Arslan** [aidenlx/obsidian-zotero#81]
Thank you for this plugin. I really look forward to using this. I'm not sure what I'm doing wrong but I'm getting dosens of error: "Citekey: No item found for itemID 7953 magazine2022". 

Any suggestion or idea what I might be missing?

I have:
- The obsidian plugin
- The Zotero add on

I tried:
- Uninstall & reinstall the obsidian plugin
- Delete "better-sqlite3" & manual install it again

**Comment by aidenlx** [comment]
can you try latest 1.0.0 and see if the issue persists? Feel free to re-open this issue if you still have similar issue.
