### ISSUE TITLE
The plugin does not recognize the literature notes until refresh the folder in settings

### ISSUE THREAD

**Issue by zhechenghu** [aidenlx/obsidian-zotero#84]
First, thanks for developing such an excellent plugin for literature reading! But I have encountered some issues.

I start up obsidian, and there is no error or warning, but the plugin does not recognize the literature note:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/100691508/201060102-c97e59fd-7ee7-45cf-b53a-e1c5ba7c49b4.png">

But it becomes normal again after resetting the note path in the settings. To be more detailed, I just clicked the circled button below and refreshed the note page. Then it becomes normal again.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/100691508/201060536-72895c45-3e51-400c-a064-4142101f23bf.png">

It would be much appreciated if you could reply! Thanks again!

**Comment by pavlohrab** [comment]
Came here to report the same bug. For me I needed to reapply note path and reopen the note.

**Comment by aidenlx** [comment]
Should be fixed in v1.0.0
