### ISSUE TITLE
Image excerpt fails

### ISSUE THREAD

**Issue by zhechenghu** [aidenlx/obsidian-zotero#85]
It leaves a vault link, but the image is not moved to the corresponding place.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/100691508/201129687-de76cc9b-4a44-4e5f-b7aa-5b6c2c773de8.png">

I can help with testing.

**Comment by aidenlx** [comment]
can you try latest 1.0.0 and see if the issue persists? Feel free to re-open this issue if you still have similar issue.

**Comment by SIAndersson** [comment]
I am having the same issue; no images are being imported. Everything else works well so far, but it doesn't seem as if the images are imported whatsoever.
