### ISSUE TITLE
Bug: creators not sorted by orderIndex by default

### ISSUE THREAD

**Issue by lkhphuc** [aidenlx/obsidian-zotero#89]
![Screenshot 2022-12-06 at 14 48 56](https://user-images.githubusercontent.com/12573521/205943902-ad6fbb5e-3a6b-47c8-8b44-b8a3c70a56e9.png)

I'm looping throught the `it.creators` array to print out the list of authors but notice they are out of order, even though the `orderIndex` info is presented in the json.

FWIW, I can sort it myself in the template like this:
```
##### <% it.creators.sort((a, b) => (a.orderIndex - b.orderIndex)).forEach(function(creator){ %><%- =  creator.fullname%>, <% }) %>(<%-= it.date %>). *<%-= it.title %>*
```

**Comment by aidenlx** [comment]
should be fixed in 1.0.0
