### ISSUE TITLE
[Bug] Plugin interferes with new core Canvas plugin as of 1.1.0

### ISSUE THREAD

**Issue by WebInspectInc** [aidenlx/obsidian-zotero#91]
I was testing out the new core Canvas plugin (in the new insider release [1.1.0](https://forum.obsidian.md/t/obsidian-release-v1-1-0-insider-build/48954)) and noticed that this plugin seems to interact poorly with the new core Canvas plugin. If you create a new "card" and try typing something with the Zotero plugin enabled, the text is erased as soon as you click out of the card.

It should look like:

![2022-12-07_14-39](https://user-images.githubusercontent.com/963985/206291005-4f298845-1dad-4993-8506-8adef2769bec.png)

But instead your text disappears once you click off the card:

![2022-12-07_14-40](https://user-images.githubusercontent.com/963985/206291035-69d166d1-9f88-4b6b-94fc-62b3a4569cd9.png)

And every character typed results in an error in the console:

![2022-12-07_14-40_1](https://user-images.githubusercontent.com/963985/206291103-cf6c5d28-304d-44a1-b624-5ef6ecc5ef94.png)

Disabling the Zotero plugin solves the problem.

**Comment by vguillet** [comment]
Came here to report the same thing, looking forward to it getting fixed as I already use this plugin a lot, and would love to be able to use it in parallel to the canvas update!

**Comment by aidenlx** [comment]
fixed in v1.0.0
