### ISSUE TITLE
[Bug] Unable to index Zotero DB and zotero quick search to open corresponding note

### ISSUE THREAD

**Issue by cs-mshah** [aidenlx/obsidian-zotero#93]
I am unable to connect my zotero database to my main obsidian vault. I tried doing it with a different vault and it worked. But I am unable to connect to zotero with main vault. It shows the following error:
![image](https://user-images.githubusercontent.com/56499208/207642560-39a72c2c-f878-4e77-93d4-2c019b3b5ac3.png)
I tried uninstalling and reinstalling the `better-sqlite3-7.6.2-mod.2.node` but the issue still remains. I tried this extension on another dummy vault and it works as expected

**Comment by aidenlx** [comment]
Should be fixed with v1.0.0 update
