### ISSUE TITLE
[Feature Request] Sort annotations by location within the text

### ISSUE THREAD

**Issue by JBrandonS** [aidenlx/obsidian-zotero#95]
Zotero annotations seem to be placed in obsidian at random, or at least in no clear order. I think it would be very useful, and the expected behavior, to have these sorted by location within the text.

Below, I have this code for the `zt-annots.eta` file which appears to sort everything correctly but I have not confirmed that same page annotations are sorted by location within the page, if anyone has a better script that would be great. 

As it stands I'd recommend the default template for `zt-annots.eta` be changed to do this:

```zt-annots.eta
<% it.sort((a,b) => (a.pageLabel - b.pageLabel)).forEach(function(annotation) { %>
<%~ include("annotation", annotation) %>
<% }) %>
```

**Comment by aidenlx** [comment]
Fixed in latest 1.0.0 plugin
