### ISSUE TITLE
[BUG] Plugin incompatible with latest obsidian installer version

### ISSUE THREAD

**Issue by cs-mshah** [aidenlx/obsidian-zotero#96]
![image](https://user-images.githubusercontent.com/56499208/210042323-96239eb2-4c7c-4a70-9ef9-2b8d0bedcbcc.png)

![image](https://user-images.githubusercontent.com/56499208/210042181-9c67ccf0-f51d-4065-a7f7-3dfb24a07fd4.png)

**Comment by krillin666** [comment]
Same issue here !

**Comment by vautrin93** [comment]
Same here!

**Comment by JBrandonS** [comment]
+1

**Comment by jwolfe99** [comment]
Sam here. Big issue

**Comment by aidenlx** [comment]
The next update on zotero and obsidian plugin will arrive in a week or two. It's a rather major update, sorry for the long wait!

**Comment by MSBack** [comment]
@aidenlx Hi, is there any update on the progress with this next update? I am eager to try the plugin, but due to this issue, I cannot.

**Comment by xuey06** [comment]
same issues！！

**Comment by aidenlx** [comment]
v1.0.0 support latest obsidian version, make sure to update zotero plugin manually as well!
